const express = require('express')
const AuthRoute = require('./routes/auth')
const UsersRoute = require('./routes/users')
const PlansRoute = require('./routes/plans')
const InvoicesRoute = require('./routes/invoices')
const UnilevelRoute = require('./routes/unilevel')
const BinaryRoute = require('./routes/binary')
const DirectRoute = require('./routes/direct')
const TransactionsRoute = require('./routes/transactions')
const WebhookRoute = require('./routes/webhook')
const WithdrawRoute = require('./routes/withdraw')
const PaymentRoute = require('./routes/payment')
const RobotRoute = require('./routes/robot')
const CareerPlanRoute = require('./routes/careerplan')
const AdminRoute = require('./routes/admin')
const OTPRoute = require('./routes/otp')
const PinRoute = require('./routes/pin')

const apiRouter = express.Router()

new AuthRoute(apiRouter)
new UsersRoute(apiRouter)
new PlansRoute(apiRouter)
new InvoicesRoute(apiRouter)
new UnilevelRoute(apiRouter)
new BinaryRoute(apiRouter)
new DirectRoute(apiRouter)
new TransactionsRoute(apiRouter)
new WebhookRoute(apiRouter)
new WithdrawRoute(apiRouter)
new PaymentRoute(apiRouter)
new RobotRoute(apiRouter)
new CareerPlanRoute(apiRouter)
new PinRoute(apiRouter)
new OTPRoute(apiRouter)
new AdminRoute(apiRouter)

module.exports = apiRouter