runtime: nodejs10

env_variables:
  BLOCKIO_API_KEY_TESTNET: 'f87f-68a8-0e30-00ed'
  BLOCKIO_API_KEY: '7a50-479c-24f5-d282'
  BLOCKIO_PIN: '09397798979'
  BLOCKIO_WEBHOOK_URL: 'https://test-api.appspot.com/api/webhook'
  
  JWT_SECRET: '1j2kDBMToTiBas6v5OWPmrbJbfoBOaSQz4'
  JWT_EXPIRATION: '20m'

  PGHOST: '/cloudsql/test-api:europe-west1:test'
  PGUSER: 'postgres'
  PGDATABASE: 'postgres'
  PGPASSWORD: 'postgres'
  PGPORT: 5432